Created by smoke tests for the feature 'workspaces', at 2019-01-03T19:07:52Z

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,32 +1,42 @@
-version: 2
+# features/workspaces
+version: 2.1
+
+executors:
+  my-executor:
+    docker:
+      - image: "circleci/clojure:latest"
+    working_directory: /tmp
+
 jobs:
-  build:
-    docker:
-      - image: circleci/ruby:2.4.1-jessie
+  upstream:
+    executor: my-executor
     steps:
-      - checkout
-      - run: 'sleep 30 && echo "A first hello"'
-  build-again:
-    docker:
-      - image: circleci/ruby:2.4.1-jessie
+      - run: mkdir -p workspace
+      - run: echo "Hello" > workspace/important-data
+      - persist_to_workspace:
+          root: workspace
+          paths:
+            - important-data
+
+  downstream:
+    executor: my-executor
     steps:
-      - checkout
-      - run: echo "Second hello"
-  build-third:
-    docker:
-      - image: circleci/ruby:2.4.1-jessie
-    steps:
-      - checkout
-      - run: echo "Third hello" && exit 1
+      - attach_workspace:
+          at: /tmp/workspace
+      - run: |
+          if [[ $(cat /tmp/workspace/important-data) == "Hello" ]]; then
+            echo "It worked!"
+          else
+            echo "My important data is missing!"
+            exit 1
+          fi
 
 workflows:
-  version: 2
-  testing:
+  version: 2.1
+
+  build:
     jobs:
-      - build
-      - build-again
-      - build-third
-  testing-again:
-    jobs:
-      - build-again
-      - build
+      - upstream
+      - downstream:
+          requires:
+            - upstream
